### ISSUE TITLE
Need help and advice from those who with sucsessful training SimSwap

### ISSUE THREAD

**Issue by netrunner-exe** [a312863063/SimSwap-train#14]
I just need advice from people who know and are able to train SimSwap. Some of my questions will seem silly, but I ask you to treat them with understanding. I am currently working to launch a train on Google Colab. I managed to do this with `-image_size 400 --display_winsize 400` (this is max), if `512` - cuda is out of memory. The training is in progress, img files are being created in the web/images folder.

1. How can I pause the training and continue from the same place in other session? If possible - please give a complete example of the command.

2. After the end of the training - if I understood correctly - are the files latest_net_D1.pth, latest_net_D2.pth, latest_net_G.pth created? If I understand correctly - is this my trained model?

3. Can I change the amount of End of epoch? It shows 20,000 for me. Example -> (End of epoch 4 / 20,000). May i set 400 or 500?

Unfortunately, I have not been involved in training models before, this is a new experience for me and I am trying to learn more and more in detail.

Perhaps someone who has already been trained in SimSwap will agree to write more detailed instructions on how to properly train a model, with all the stages and examples, this would greatly help the entire community.

**Comment by a312863063** [comment]
good luck！

**Comment by realisticdreamer114514** [comment]
For 2), if the folder (say) ./checkpoints/CelebA_512_finetune has the same structure as ./checkpoints/people, it is the trained model.  

Have you found out the solutions for the other 2 questions?
