### ISSUE TITLE
Can't create faceset from celebA dataset

### ISSUE THREAD

**Issue by netrunner-exe** [a312863063/SimSwap-train#18]
When i run make_dataset.py, it just show `0it [00:00, ?it/s]`
```
find model: ./insightface_func/models/antelope/glintr100.onnx recognition
find model: ./insightface_func/models/antelope/scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
0it [00:00, ?it/s]
```
and not make dataset, just make empty folders - imgs and latents.

Images from CelebA dataset (around 10.000) are in the root of the folder SimSwap-train/dataset/CelebA
Lines in `face_align.py` was modified like in readme.

**Comment by Gitgutx** [comment]
Hello, I'm trying to reproduce the training on Colab and I have this same error, how to fix it?
If you have a working Colab notebook can you share, please?

Thank you.
