### ISSUE TITLE
Can't download 256px-pretrained-weight

### ISSUE THREAD

**Issue by netrunner-exe** [a312863063/SimSwap-train#36]
Hi @a312863063, please upload 256px-pretrained-weight to Google drive or DropBox in order to be able to download for those users who cannot download from Baidu drive. 嗨 @a312863063，请将 256px-pretrained-weight 上传到谷歌驱动器或 DropBox，以便那些无法从百度驱动器下载的用户能够下载。

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give for free. Honestly, that’s pretty cheap compared to most of these services.
