### ISSUE TITLE
大佬可以复现GPEN的训练代码吗？

### ISSUE THREAD

**Issue by CongYuSanXun** [a312863063/SimSwap-train#5]
项目地址：https://github.com/yangxy/GPEN
提前感谢！

**Comment by a312863063** [comment]
哈，我了解他们组。我估计他们是希望把这个技术用在业务上的，我不给他们添麻烦哈～

**Comment by CongYuSanXun** [comment]
> 哈，我知道他们组。我估计他们是希望把这个技术用在业务上的，我不给他们添麻烦哈～

明白了，谢谢大佬的回复！
